### ISSUE TITLE
Nutrition grade is displayed for products that don't have it

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2057]
https://world.openfoodfacts.org/api/v0/product/3228675443053.json
Doesn't have a nutrition grade BUT shown as B in the Products to be completed list

![image](https://user-images.githubusercontent.com/1689815/50600599-dd851f00-0eb1-11e9-961e-561d7a7ed083.png)

**Comment by jaindiv26** [comment]
@teolemon I'll investigate this issue.

**Comment by teolemon** [comment]
thnak @jaindiv26 :-)

**Comment by deniger** [comment]
Should be fixed with #2124 by @subhanjansaha
![image](https://user-images.githubusercontent.com/47569605/55335985-7705a200-549c-11e9-87fd-7c6fc9b2f7b3.png)

**Comment by teolemon** [comment]
@deniger Still an issue where No Nutriscore appears while one exists.
![image](https://user-images.githubusercontent.com/1689815/55336254-eda29f80-549c-11e9-8e34-99f42fb73264.png)
![image](https://user-images.githubusercontent.com/1689815/55336262-f1cebd00-549c-11e9-8b3d-4c98ed444487.png)
