### ISSUE TITLE
Button alignment issue in the Additives cards

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3673]
Button alignment issue in the Additives cards

"Browse products" and "View on Wikipedia" are not aligned.

![image](https://user-images.githubusercontent.com/1689815/103483317-ac17f480-4de6-11eb-8cc9-69b818e5ed94.png)

**Comment by kartikaysharma01** [comment]
I think this is fixed. @teolemon 
Can you re-check and give product barcode if you are able to reproduce.

**Comment by mrudultora** [comment]
@teolemon  When the language is set as English the buttons are aligned correctly. I tried changing my device default language to french but the text still appears in english. Some part appears in french. Have a look at the image. (Changed the language to french even from Preferences).
(View on Wikipedia must change to Voir Sur Wikipedia according to Strings.xml)
![Image](https://user-images.githubusercontent.com/65870389/104287805-fa12b380-54dc-11eb-82d8-1a541ebd71c9.jpeg)

**Comment by mrudultora** [comment]
I am able to produce this issue after changing the length of Browse Products to something longer. 
![Untitled](https://user-images.githubusercontent.com/65870389/104291924-2c72df80-54e2-11eb-9ece-9901f6001b9e.png)
