### ISSUE TITLE
Allergen alerts are broken in the internal build (on the product page)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3943]
Allergen alerts are broken in the internal build (on the product page)

**Comment by VaiTon** [comment]
@teolemon could you provide steps to reproduce?

**Comment by teolemon** [comment]
0. Can't open the app anymore
1. Add gluten alert
2. Scan gluten product

**Comment by VaiTon** [comment]
> 0. Can't open the app anymore

This one should be fixed by the latest commits.

**Comment by teolemon** [comment]
Still happening (but I can now open the app). Adding to next release milestone and pinning

**Comment by teolemon** [comment]
```
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:3: Pb(390) The import org.greenrobot cannot be resolved.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:4: Pb(390) The import org.greenrobot cannot be resolved.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:5: Pb(390) The import org.greenrobot cannot be resolved.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:6: Pb(390) The import org.greenrobot cannot be resolved.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:7: Pb(390) The import org.greenrobot cannot be resolved.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:8: Pb(390) The import org.greenrobot cannot be resolved.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:9: Pb(390) The import org.greenrobot cannot be resolved.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:10: Pb(390) The import org.greenrobot cannot be resolved.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:11: Pb(390) The import org.greenrobot cannot be resolved.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:15: Pb(390) The import openfoodfacts.github.scrachx.openfood.models.DaoSession cannot be resolved.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:17: Pb(2) Entity cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:18: Pb(2) Index cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:21: Pb(2) Id cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:23: Pb(2) Unique cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:28: Pb(2) Unique cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:33: Pb(2) ToMany cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:34: Pb(2) JoinProperty cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:36: Pb(2) AllergenName cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:41: Pb(2) Generated cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:42: Pb(2) DaoSession cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:47: Pb(2) Generated cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:48: Pb(2) AllergenDao cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:50: Pb(2) Generated cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:60: Pb(2) Keep cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:61: Pb(2) AllergenName cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:64: Pb(2) AllergenName cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:69: Pb(2) Keep cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:70: Pb(2) AllergenName cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:73: Pb(2) AllergenName cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:77: Pb(2) Generated cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:101: Pb(2) Generated cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:102: Pb(2) AllergenName cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:103: Pb(2) AllergenName cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:104: Pb(2) DaoSession cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:104: Pb(2) DaoSession cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:106: Pb(2) DaoException cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:108: Pb(2) AllergenNameDao cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:109: Pb(2) AllergenName cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:111: Pb(2) AllergenName cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:112: Pb(2) AllergenName cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:116: Pb(2) AllergenName cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:122: Pb(2) Generated cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:124: Pb(2) AllergenName cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:131: Pb(2) Generated cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:133: Pb(2) AllergenDao cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:134: Pb(2) DaoException cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:136: Pb(2) AllergenDao cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:143: Pb(2) Generated cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:145: Pb(2) AllergenDao cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:146: Pb(2) DaoException cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:148: Pb(2) AllergenDao cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:155: Pb(2) Generated cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:157: Pb(2) AllergenDao cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:158: Pb(2) DaoException cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:160: Pb(2) AllergenDao cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:191: Pb(2) Generated cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:192: Pb(2) DaoSession cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:193: Pb(2) DaoSession cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java:194: Pb(2) AllergenDao cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/AllergenName.java:3: Pb(390) The import org.greenrobot cannot be resolved.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/AllergenName.java:4: Pb(390) The import org.greenrobot cannot be resolved.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/AllergenName.java:5: Pb(390) The import org.greenrobot cannot be resolved.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/AllergenName.java:6: Pb(390) The import org.greenrobot cannot be resolved.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/AllergenName.java:7: Pb(390) The import org.greenrobot cannot be resolved.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/AllergenName.java:15: Pb(2) Entity cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/AllergenName.java:16: Pb(2) Index cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/AllergenName.java:19: Pb(2) Id cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/AllergenName.java:27: Pb(2) Generated cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/AllergenName.java:38: Pb(2) Keep cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/AllergenName.java:48: Pb(2) Keep cannot be resolved to a type.
[Verbose] Ignoring parser problem in /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/AllergenName.java:57: Pb(2) Generated cannot be resolved to a type.
```

**Comment by VaiTon** [comment]
@teolemon which product are you testing?

**Comment by teolemon** [comment]
Code-barres:3770007763952
This one for instance, after setting a gluten alert

**Comment by VaiTon** [comment]
@teolemon 
https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/7828b96526aa7e1d055a9c99ef5c04b30c1e801c/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/AllergenHelper.kt#L15
what should we do?
